export function createDifficultyProfiles(defaultLives) {
  return {
    nebula: {
      name: 'Nebula Run',
      description: 'Generous lives and a calmer ball speed ideal for warm-ups.',
      startLevel: 1,
      lives: 5,
      speedMultiplier: 0.85,
      growthMultiplier: 0.75,
      maxSpeedMultiplier: 0.8,
      musicTheme: 'Synthwave Nebula',
    },
    garden: {
      name: 'Cosmic Bloom',
      description: 'Balanced challenge with standard lives and tempo.',
      startLevel: 2,
      lives: defaultLives,
      speedMultiplier: 1,
      growthMultiplier: 1,
      maxSpeedMultiplier: 1,
      musicTheme: 'Cosmic Garden',
    },
    station: {
      name: 'Orbital Siege',
      description: 'Fewer lives, faster ball, and a steeper speed curve.',
      startLevel: 3,
      lives: 2,
      speedMultiplier: 1.12,
      growthMultiplier: 1.25,
      maxSpeedMultiplier: 1.2,
      musicTheme: 'Orbital Station',
    },
    aurora: {
      name: 'Aurora Peaks',
      description: 'Icy ridges, reflective ice and gusty winds challenge positioning.',
      startLevel: 4,
      lives: 4,
      speedMultiplier: 0.95,
      growthMultiplier: 1.05,
      maxSpeedMultiplier: 1,
      musicTheme: 'Aurora Peaks',
    },
    mirage: {
      name: 'Desert Mirage',
      description: 'Shimmering dunes with erratic gusts and heat-driven rebounds.',
      startLevel: 5,
      lives: 3,
      speedMultiplier: 1.05,
      growthMultiplier: 1.2,
      maxSpeedMultiplier: 1.1,
      musicTheme: 'Desert Mirage',
    },
    neon: {
      name: 'Neon Shards',
      description: 'Hyper-fast rails, dense grids, and relentless ball acceleration.',
      startLevel: 6,
      lives: 2,
      speedMultiplier: 1.15,
      growthMultiplier: 1.3,
      maxSpeedMultiplier: 1.25,
      musicTheme: 'Neon Shards',
    },
  };
}
